"""
NVIDIA NIM — Nemotron clinical reasoning client
===============================================
Talks to NVIDIA's HOSTED NIM endpoint (integrate.api.nvidia.com), which is
OpenAI-compatible and runs the model on NVIDIA's GPUs. That matters here
because it needs only an API key — no local CUDA device, no Docker, no NGC
container pull. Self-hosted NIM and Triton/TensorRT-LLM both require a local
NVIDIA GPU, which this deployment does not have.

WHERE THIS SITS IN THE SYSTEM — read this before using it anywhere else:

    The LLM writes PROSE. It does not decide anything.

    Triage level, alert firing, and every clinical threshold are decided by
    jev_engine.py and the deterministic rules BEFORE this module is called.
    Nemotron is handed the verdict that was already reached and asked to
    explain it to a nurse in plain language. Its output then passes through
    guardrails.py, which rejects any wording that contradicts that verdict.

    So the worst a model failure can do is produce no explanation. It can
    never change, delay, or suppress an alert:
      - it is never called on the alert path
      - it runs with a hard timeout
      - every failure returns None and the caller falls back to rule text
"""

import asyncio
import logging
import os
from typing import Dict, List, Optional

import httpx

logger = logging.getLogger("vitalband.nvidia_nim")

# NVIDIA's hosted, OpenAI-compatible inference gateway.
NIM_BASE_URL = os.getenv("NVIDIA_NIM_BASE_URL", "https://integrate.api.nvidia.com/v1")

# Pick any Nemotron build from build.nvidia.com and set NVIDIA_NIM_MODEL to it.
NIM_MODEL = os.getenv("NVIDIA_NIM_MODEL", "nvidia/llama-3.1-nemotron-70b-instruct")

API_KEY = os.getenv("NVIDIA_API_KEY", "").strip()

# Short on purpose. A nurse-facing explanation that arrives late is worthless,
# and nothing downstream is allowed to wait on it.
REQUEST_TIMEOUT_S = float(os.getenv("NVIDIA_NIM_TIMEOUT", "4.0"))
MAX_TOKENS = 220

SYSTEM_PROMPT = (
    "You are a clinical communication assistant inside a hospital triage dashboard. "
    "A deterministic rule engine has ALREADY decided this patient's triage level. "
    "Your only job is to explain that decision to a busy nurse in plain English.\n\n"
    "Hard rules:\n"
    "1. NEVER contradict, soften, question or re-rank the given triage level.\n"
    "2. NEVER tell anyone to ignore, dismiss, delay or stand down an alert.\n"
    "3. NEVER invent vitals, history, diagnoses or numbers you were not given.\n"
    "4. Do not diagnose. Describe what the readings show and what to check.\n"
    "5. Maximum 3 short sentences. No preamble, no bullet points, no headings."
)


def is_configured() -> bool:
    return bool(API_KEY)


def status() -> Dict:
    """Honest description of what is actually wired up right now."""
    return {
        "service": "NVIDIA NIM · Nemotron",
        "configured": is_configured(),
        "mode": "hosted" if is_configured() else "disabled",
        "base_url": NIM_BASE_URL,
        "model": NIM_MODEL if is_configured() else None,
        "role": "explanation only — never decides triage",
        "detail": (
            "Live: explanations generated by Nemotron on NVIDIA-hosted GPUs."
            if is_configured()
            else "No NVIDIA_API_KEY set. Falling back to deterministic rule text."
        ),
    }


def _build_user_prompt(ctx: Dict) -> str:
    lines = [
        f"Patient: {ctx.get('patient_id', 'unknown')}",
        f"Triage level already decided: {ctx.get('triage_level', 'UNKNOWN')}",
        f"Decided by: {'deterministic clinical rule' if ctx.get('deterministic_override') else 'trend index'}",
    ]
    if ctx.get("heart_rate") is not None:
        lines.append(f"Heart rate: {ctx['heart_rate']} BPM")
    if ctx.get("spo2") is not None:
        lines.append(f"SpO2: {ctx['spo2']}%")
    if ctx.get("deterioration_index") is not None:
        lines.append(f"Deterioration index: {ctx['deterioration_index']}/100")
    if ctx.get("sos"):
        lines.append("Patient pressed the SOS button.")
    if ctx.get("fall"):
        lines.append("A fall was confirmed by the camera.")

    contributors: List[Dict] = ctx.get("contributors") or []
    if contributors:
        lines.append("Contributing factors, largest first:")
        for c in contributors[:4]:
            lines.append(f"  - {c.get('factor')}: {c.get('value')}")

    if ctx.get("rule_reason"):
        lines.append(f"Rule engine reason: {ctx['rule_reason']}")

    lines.append(
        "\nExplain this triage decision to the nurse in at most 3 short sentences."
    )
    return "\n".join(lines)


async def explain_triage(ctx: Dict) -> Optional[str]:
    """
    Returns a nurse-facing explanation, or None on any failure.

    None is an entirely normal outcome — the caller must already have usable
    rule-based text to show.
    """
    if not is_configured():
        return None

    payload = {
        "model": NIM_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": _build_user_prompt(ctx)},
        ],
        "temperature": 0.2,      # low: this is explanation, not creativity
        "top_p": 0.9,
        "max_tokens": MAX_TOKENS,
        "stream": False,
    }
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Accept": "application/json",
        "Content-Type": "application/json",
    }

    try:
        async with httpx.AsyncClient(timeout=REQUEST_TIMEOUT_S) as client:
            r = await client.post(
                f"{NIM_BASE_URL}/chat/completions", json=payload, headers=headers
            )
        if r.status_code != 200:
            logger.warning("NIM returned %s: %s", r.status_code, r.text[:200])
            return None

        data = r.json()
        choices = data.get("choices") or []
        if not choices:
            return None
        text = (choices[0].get("message") or {}).get("content", "").strip()
        return text or None

    except (httpx.TimeoutException, asyncio.TimeoutError):
        logger.warning("NIM timed out after %.1fs — using rule text", REQUEST_TIMEOUT_S)
        return None
    except Exception as e:
        logger.warning("NIM call failed (%s) — using rule text", e)
        return None
